import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  BarChart3,
  Bell,
  BookmarkPlus,
  Bot,
  Brain,
  Calendar,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ClipboardCheck,
  Clock,
  CircleDollarSign,
  CircleHelp,
  CirclePlus,
  Copy,
  Eye,
  FileDown,
  FileText,
  Flag,
  Gauge,
  Heart,
  History,
  Home,
  Image as ImageIcon,
  KeyRound,
  ListChecks,
  LogIn,
  LayoutDashboard,
  LogOut,
  Maximize,
  Menu,
  MessageCircle,
  MoreVertical,
  MonitorCog,
  Palette,
  PanelLeftOpen,
  PenLine,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Snowflake,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  TrendingUp,
  Trash2,
  Upload,
  UserCircle,
  Users,
  WandSparkles,
  X,
  XCircle,
  type LucideIcon
} from "lucide-react";
import { cn } from "@/lib/utils";

const icons: Record<string, LucideIcon> = {
  account_balance_wallet: CircleDollarSign,
  account_circle: UserCircle,
  ac_unit: Snowflake,
  add: CirclePlus,
  add_circle: CirclePlus,
  ads_click: Target,
  analytics: BarChart3,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  article: FileText,
  auto_awesome: Sparkles,
  auto_graph: Activity,
  autorenew: RefreshCw,
  bar_chart: BarChart3,
  block: Ban,
  bookmark_add: BookmarkPlus,
  bolt: WandSparkles,
  campaign: Gauge,
  cancel: XCircle,
  calendar_month: Calendar,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  chat_bubble: MessageCircle,
  close: X,
  contact_support: Bot,
  content_copy: Copy,
  dashboard: LayoutDashboard,
  delete: Trash2,
  download: FileDown,
  edit_square: PenLine,
  edit_note: PenLine,
  error: AlertTriangle,
  fact_check: ClipboardCheck,
  favorite: Heart,
  file_download: FileDown,
  flag: Flag,
  folder_copy: FileText,
  group: Users,
  groups: Users,
  help_outline: CircleHelp,
  history: History,
  home: Home,
  hourglass_top: Clock,
  hub: Share2,
  image: ImageIcon,
  insights: WandSparkles,
  interests: Sparkles,
  info: CircleHelp,
  inventory_2: FileText,
  key: KeyRound,
  keyboard_arrow_down: ChevronDown,
  checklist: ListChecks,
  login: LogIn,
  logout: LogOut,
  menu: Menu,
  menu_open: PanelLeftOpen,
  monitoring: MonitorCog,
  more_vert: MoreVertical,
  notifications: Bell,
  palette: Palette,
  post_add: PenLine,
  edit_calendar: Calendar,
  refresh: RefreshCw,
  rocket_launch: Rocket,
  publish: Send,
  save: CheckCircle2,
  schedule_send: Clock,
  schedule: Clock,
  search: Search,
  send: Send,
  settings: Settings,
  admin_panel_settings: ShieldCheck,
  shopping_cart_checkout: ShoppingCart,
  space_dashboard: LayoutDashboard,
  star: Star,
  star_border: Star,
  sticky_note_2: FileText,
  sync: RefreshCw,
  terminal: Bot,
  lightbulb: Sparkles,
  thumb_up: ThumbsUp,
  trending_up: TrendingUp,
  tune: MonitorCog,
  upload_file: Upload,
  verified: CheckCircle2,
  visibility: Eye,
  warning: AlertTriangle
};

export function MaterialIcon({
  name,
  filled = false,
  className
}: {
  name: string;
  filled?: boolean;
  className?: string;
}) {
  const Icon = icons[name] ?? CircleHelp;

  return (
    <Icon
      aria-hidden="true"
      className={cn("h-[1em] w-[1em] shrink-0 text-[24px] stroke-[2]", filled && "stroke-[2.4]", className)}
    />
  );
}
